version: '3'
services:
  db.apontamento:
    container_name: db.apontamento
    restart: unless-stopped
    image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrongPassword!
    ports:
      - "6433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql:rw

  api.apontamento:
    container_name: api.apontamento
    image: api_apontamento
    build:
      context: ./Apontamento
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "6001:6001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:6001
      - ConnectionStrings__DefaultConnection=Server=db.apontamento,1433;Database=aspnet-Apontamento;User Id=sa;Password=yourStrongPassword!;
    depends_on:
      db.apontamento:
        condition: service_started
  #
  # portainer:
  #   container_name: portainer
  #   image: portainer/portainer-ce:alpine
  #   restart: unless-stopped
  #   ports:
  #     - "9001:9000"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - portainer_data:/data
  #
  # swag:
  #   container_name: swag
  #   image: linuxserver/swag:1.25.0
  #   restart: unless-stopped
  #   cap_add:
  #     - NET_ADMIN
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/Sao_Paulo
  #     - VALIDATION=http
  #     - URL=well1ngton.site
  #     - SUBDOMAINS=www,api,portainer,heimdall
  #     - ONLY_SUBDOMAINS=false
  #     - STAGING=false
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - swag_data:/config
  #
  # heimdall:
  #   container_name: heimdall
  #   image: ghcr.io/linuxserver/heimdall
  #   restart: unless-stopped
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/Sao_Paulo
  #   volumes:
  #     - heimdall_data:/config

volumes:
  sqlserver_data:
    # swag_data:
    # portainer_data:
    # heimdall_data:
